#!/usr/bin/env bash

set -e

# readlink -f but works on macOS too
resolve_link() {
  local target="$1"
  while [ -L "$target" ]; do
    target="$(readlink "$target")"
    if [[ "$target" != /* ]]; then
      target="$(dirname "$1")/$target"
    fi
  done
  echo "$target"
}

BASE_DIR=$(cd -- "$(dirname -- "$(resolve_link "${BASH_SOURCE:-$0}")")" &>/dev/null && pwd)
if [ ! -d "$BASE_DIR/node_modules" ] || [ ! -x "$BASE_DIR/dist/runner/index.js" ]; then
    "$BASE_DIR/setup.sh"
fi

exec -a cliweb node "$BASE_DIR/dist/runner/index.js" "$@"
