#!/usr/bin/env bash
set -euo pipefail

# Based off of https://bun.sh/install

DOWNLOAD_TO=${DOWNLOAD_TO-"$HOME/cliweb"}
INSTALL_TO=${INSTALL_TO-"$HOME/.local"}

REPO='https://github.com/atomashevic/cliweb'
BRANCH='electron'
ZIP="${BRANCH}.zip"
ZIP_URI="$REPO/archive/refs/heads/$ZIP"

# Reset
Color_Off=''

# Regular Colors
Red=''
Green=''
Dim='' # White

# Bold
Bold_White=''
Bold_Green=''

if [[ -t 1 ]]; then
  # Reset
  Color_Off='\033[0m' # Text Reset

  # Regular Colors
  Red='\033[0;31m'   # Red
  Green='\033[0;32m' # Green
  Dim='\033[0;2m'    # White

  # Bold
  Bold_Green='\033[1;32m' # Bold Green
  Bold_White='\033[1m'    # Bold White
fi

error() {
  echo -e "${Red}error${Color_Off}:" "$@" >&2
  exit 1
}

info() {
  echo -e "${Dim}$@ ${Color_Off}"
}

info_bold() {
  echo -e "${Bold_White}$@ ${Color_Off}"
}

success() {
  echo -e "${Green}$@ ${Color_Off}"
}

tildify() {
  if [[ $1 = $HOME/* ]]; then
    local replacement=\~/

    echo "${1/$HOME\//$replacement}"
  else
    echo "$1"
  fi
}

bin_dir="$INSTALL_TO/bin"
add_to_path=false

if [[ ! -d $bin_dir ]]; then
  mkdir -p "$bin_dir" || error "Failed to create install directory \"$bin_dir\""
  add_to_path=true
fi

if which git >/dev/null; then
  if [[ -d "$DOWNLOAD_TO" ]]; then
    info_bold "Updating cliweb using git"
    (cd "$DOWNLOAD_TO" && (git pull || error "Failed to pull cliweb in \"$DOWNLOAD_TO\""))
  else
    info_bold "Downloading cliweb using git"
    git clone $REPO $DOWNLOAD_TO || error "Failed to clone cliweb to \"$DOWNLOAD_TO\""
  fi
else
  info_bold ""
  command -v unzip >/dev/null || error 'unzip is required to install cliweb'
  mkdir -p "$bin_dir" || error "Failed to create cliweb directory \"$DOWNLOAD_TO\""

  zip_file="$DOWNLOAD_TO/$ZIP"
  curl --fail --location --progress-bar --output $zip_file "$ZIP_URI" ||
    error "Failed to download cliweb from \"$ZIP_URI\""
      config_path="$DOWNLOAD_TO/config.js"
      config_exists=false
      if [[ -f $config_path ]]; then
        config_exists=true
        mv "$config_path" "${config_path}.bak"
      fi

      unzip -oqd "$DOWNLOAD_TO" $zip_file ||
        error 'Failed to extract cliweb'

      chmod +x \
        "$DOWNLOAD_TO/setup.sh" \
        "$DOWNLOAD_TO/cliweb" \
        "$DOWNLOAD_TO/cliwebctl" \
        "$DOWNLOAD_TO/install-control-cliweb-skill"
      rm $zip_file
fi

(cd "$DOWNLOAD_TO" && bash setup.sh)

echo

# Install command links.
for command in cliweb cliwebctl; do
  exe="$bin_dir/$command"
  if [[ ! -e $exe ]]; then
    (cd "$bin_dir" && ln -s "$DOWNLOAD_TO/$command")
  else
    info_bold "$(tildify $exe) already exists, skipping link install"
    echo
  fi
done

# Install path if necessary
if [[ $add_to_path = false ]]; then
  success "cliweb was successfully installed to $Bold_Green$(tildify $DOWNLOAD_TO)"
  echo
  info "To get started, run:"
  info_bold "  cliweb --help"
  info_bold "  cliwebctl help"
  exit 0
fi

refresh_command=''

install_dir="$DOWNLOAD_TO"
tilde_bin_dir=$(tildify "$bin_dir")

case $(basename "$SHELL") in
  fish)
    commands=(
      "set --export PATH $bin_dir \$PATH"
    )

    fish_config=$HOME/.config/fish/config.fish
    tilde_fish_config=$(tildify "$fish_config")

    if [[ -w $fish_config ]]; then
      {
        echo -e '\n# cliweb'

        for command in "${commands[@]}"; do
          echo "$command"
        done
      } >>"$fish_config"

      info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_fish_config\""

      refresh_command="source $(tildify $tilde_fish_config)"
    else
      echo "Manually add the directory to $tilde_fish_config (or similar):"

      for command in "${commands[@]}"; do
        info_bold "  $command"
      done
    fi
    ;;
  zsh)
    commands=(
      "export PATH=\"$bin_dir:\$PATH\""
    )

    zsh_config=$HOME/.zshrc
    tilde_zsh_config=$(tildify "$zsh_config")

    if [[ -w $zsh_config ]]; then
      {
        echo -e '\n# cliweb'

        for command in "${commands[@]}"; do
          echo "$command"
        done
      } >>"$zsh_config"

      info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_zsh_config\""

      refresh_command="exec $SHELL"
    else
      echo "Manually add $tilde_bin_dir to $tilde_zsh_config (or similar):"

      for command in "${commands[@]}"; do
        info_bold "  $command"
      done
    fi
    ;;
  bash)
    commands=(
      "export PATH=\"$bin_dir:\$PATH\""
    )

    bash_configs=(
      "$HOME/.bashrc"
      "$HOME/.bash_profile"
    )

    if [[ ${XDG_CONFIG_HOME:-} ]]; then
      bash_configs+=(
      "$XDG_CONFIG_HOME/.bash_profile"
      "$XDG_CONFIG_HOME/.bashrc"
      "$XDG_CONFIG_HOME/bash_profile"
      "$XDG_CONFIG_HOME/bashrc"
    )
    fi

    set_manually=true
    for bash_config in "${bash_configs[@]}"; do
      tilde_bash_config=$(tildify "$bash_config")

      if [[ -w $bash_config ]]; then
        {
          echo -e '\n# cliweb'

          for command in "${commands[@]}"; do
            echo "$command"
          done
        } >>"$bash_config"

        info "Added \"$tilde_bin_dir\" to \$PATH in \"$tilde_bash_config\""

        refresh_command="source $(tildify $bash_config)"
        set_manually=false
        break
      fi
    done

    if [[ $set_manually = true ]]; then
      echo "Manually add $tilde_bin_dir to $tilde_bash_config (or similar):"

      for command in "${commands[@]}"; do
        info_bold "  $command"
      done
    fi
    ;;
  *)
    echo 'Manually add the directory to ~/.bashrc (or similar):'
    info_bold "  export PATH=\"$bin_dir:\$PATH\""
    ;;
esac

echo
info "To get started, run:"

if [[ $refresh_command ]]; then
  info_bold "  $refresh_command"
fi

info_bold "  cliweb --help"
info_bold "  cliwebctl help"
